os: linux
language: generic

before_script:
  - npm install apidoc -g

script:
  - apidoc -i routes -o docs

before_deploy:
  - openssl aes-256-cbc -K $encrypted_cdd8c7bcd5fa_key -iv $encrypted_cdd8c7bcd5fa_iv -in .deploy/key.enc -out .deploy/key -d
  - chmod 600 .deploy/key
  - eval "$(ssh-agent -s)"

deploy:
  # API documentation to GitHub Pages
  - provider: pages
    skip_cleanup: true
    local_dir: docs
    github_token: $GITHUB_TOKEN
    keep_history: false
    on:
      branch: master

  # Application to the server
  - provider: script
    skip_cleanup: true
    script: rsync -e "ssh -i .deploy/key -p $SSH_PORT -o 'StrictHostKeyChecking no'" -lrtuvP --inplace --exclude-from=.deploy/exclude.txt . $SSH_USER@$SSH_HOST:$API_PATH
    on:
      branch: master

notification:
  webhooks: https://discordapp.com/api/webhooks/620036919220371486/jTbZ1-JNe4amUAKmV2w1Ru_tEm69DscTz7HpkX3fB3C_grGDvtbXmdXysr98RduFu3N3
