os: linux

language: generic

before_script:
  - npm install apidoc -g

script:
  - apidoc -i routes -o docs

deploy:
  # API documentation on GitHub Pages
  - provider: pages
    skip_cleanup: true
    local_dir: docs
    github_token: $GITHUB_TOKEN
    keep_history: false
    on:
      branch: master
