os: linux

jobs:
  include:
    - stage: "Application"
      language: php
      install: composer install
      before_deploy:
        - openssl aes-256-cbc -K $encrypted_cdd8c7bcd5fa_key -iv $encrypted_cdd8c7bcd5fa_iv -in .deploy/key.enc -out .deploy/key -d
        - chmod 600 .deploy/key
        - eval "$(ssh-agent -s)"
      deploy:
        provider: script
        skip_cleanup: true
        script: rsync -e "ssh -i .deploy/key -p $SSH_PORT -o 'StrictHostKeyChecking no'" -lrtuvP --inplace --exclude-from=.deploy/exclude.txt . $SSH_USER@$SSH_HOST:$API_PATH
        on:
          branch: master

    - stage: "Documentation"
      language: generic
      name: "apiDoc"
      install: npm install apidoc -g
      script: apidoc -i routes -o docs
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: docs
        github_token: $GITHUB_TOKEN
        keep_history: true
        on:
          branch: master
